### ISSUE TITLE
SyntaxError if the string contain a Shebang at start

### ISSUE THREAD

**Issue by fraxken** [cherow/cherow#334]
Hi,

In one of my project i use cherow to retrieve some information in my JavaScript files (require declaration). But when the file start with a shebang (a .js file for a Binary project for example), then cherow throw an SyntaxError (i suppose cherow try to parse it as Javascript but fail).

```
{ SyntaxError: Line 1, column 0: Unexpected token 'end of source'
    at constructError (F:\Code\SlimIO\psp\node_modules\cherow\dist\umd\cherow.js:5625:21)
    at report (F:\Code\SlimIO\psp\node_modules\cherow\dist\umd\cherow.js:5664:7)
    at scanPrivateName (F:\Code\SlimIO\psp\node_modules\cherow\dist\umd\cherow.js:381:11)
    at scan (F:\Code\SlimIO\psp\node_modules\cherow\dist\umd\cherow.js:1756:34)
    at nextToken (F:\Code\SlimIO\psp\node_modules\cherow\dist\umd\cherow.js:5010:30)
    at parseStatementList (F:\Code\SlimIO\psp\node_modules\cherow\dist\umd\cherow.js:7078:7)
    at parseSource (F:\Code\SlimIO\psp\node_modules\cherow\dist\umd\cherow.js:7039:11)
    at Object.parseScript (F:\Code\SlimIO\psp\node_modules\cherow\dist\umd\cherow.js:7117:14)
    at main (F:\Code\SlimIO\psp\bin\index.js:468:37)
  index: 1,
  line: 1,
  column: 0,
  description: "Unexpected token 'end of source'" }
```

To reproduce the issue, just create a .js file with a Shebang at the start:
```js
#!/usr/bin/env node

console.log("hello world");
```

And parse the script:
```js
const { readFileSync } = require("fs");

const buf = await readFileSync("./jsFile.js");
const AST = cherow.parseScript(buf.toString());
console.log(JSON.stringify(AST, null, 2));
```

A workaround is to check the first character of the Buffer and if it match "#" i will remove the complete line.

Current Behavior: SyntaxError
Expected Behavior: Ignore Shebang

Best Regards,
Thomas

**Comment by KFlash** [comment]
Hi. Are you using Cherow 1.6.9? Try use the @dev version on NPM. That's the current version on Master branch and shebang will not be skipped unless you do `{ next: true }` because it's part of ESNext and the [proposal-hashbang](https://github.com/tc39/proposal-hashbang). Hope that helps :)

**Comment by fraxken** [comment]
Hi,

Yes i'm using Cherow 1.6.9. 
I tested your solution with the dev release and it work. Thanks 💯 

Best Regards
Thomas

**Comment by KFlash** [comment]
You are welcome. I'm closing this issue then.
