### ISSUE TITLE
Incorrect Error Reporting

### ISSUE THREAD

**Issue by julianjensen** [cherow/cherow#48]
Incorrect Error Reporting
-------------------------

When I parse the files in one of my projects using `cherow` I'm getting errors where there shouldn't be any. I have tried to come up with some minimal examples that cause errors in `cherow`, samples that aren't actually errors. The examples may not make sense as they are just sections of code that failed for me that I then tried to pare down to find some sort of minimal example that would still cause the errors. They can undoubtedly be minimalized even more. The code snippets shold be fine but they'll cause `cherow` to throw the incorrect errors.

### Example 1

Giving this snippet to `cherow`

```js
cherow.parseScript(
`function a( head, tail )
{
    const defs = [ head ].concat( extract( tail, 3 ) );

    return function() {
        let errs;

        for ( const def of defs )
        {
            args.save();
            try
            {
            }
            catch ( err )
            {
                errs = err;
            }
        }

        throw errs;
    };
}` );
```

throws the following error:

```bash

/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:443
    throw createError.apply(void 0, [ type, this.getLocations() ].concat( params ));
    ^
Error: Line 14: 'err' has already been declared 
    at constructError (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:291:17)
    at createError (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:312:17)
    at Parser.error (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:443:23)
    at Parser.addBlockName (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4779:14)
    at Parser.addVarOrBlock (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4751:14)
    at Parser.parseBindingIdentifier (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4869:14)
    at Parser.parseBindingPatternOrIdentifier (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4847:25)
    at Parser.parseCatchClause (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:2556:22)
    at Parser.parseTryStatement (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:2529:24)
    at Parser.parseStatement (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:2462:25)
    at Parser.parseStatementListItem (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:2408:25)
    at Parser.parseBlockStatement (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:2510:26)
    at Parser.parseStatement (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:2422:25)
    at Parser.parseForStatement (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:2742:25)
    at Parser.parseStatement (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:2437:25)
    at Parser.parseStatementListItem (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:2408:25)
```

### Example 2

Giving this snippet to`cherow` with `{ next: true }`

```js
cherow.parseScript(
    `const    
    any = ( ...args ) => args.some( a => !!a ),
    all = ( ...args ) => args.every( a => !!a );`, { next: true } );
```

causes it to throw this error:

```bash
/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:443
    throw createError.apply(void 0, [ type, this.getLocations() ].concat( params ));
    ^
Error: Line 3: 'args' has already been declared 
    at constructError (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:291:17)
    at createError (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:312:17)
    at Parser.error (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:443:23)
    at Parser.addBlockName (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4779:14)
    at Parser.addVarOrBlock (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4751:14)
    at Parser.parseBindingIdentifier (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4869:14)
    at Parser.parseBindingPatternOrIdentifier (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4847:25)
    at Parser.parseRestElement (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4388:25)
    at Parser.parseParenthesizedExpression (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:4474:21)
    at Parser.parsePrimaryExpression (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:3945:25)
    at Parser.parseMemberExpression (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:3541:44)
    at Parser.parseLeftHandSideExpression (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:3532:25)
    at Parser.parseUpdateExpression (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:3447:17)
    at Parser.parseUnaryExpression (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:3393:21)
    at Parser.parseBinaryExpression (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:3349:44)
    at Parser.parseConditionalExpression (/Users/julian.jensen/code/v2/node_modules/cherow/dist/cherow.js:3334:21)
```

Interestingly, the following works

```js
cherow.parseScript(
    `
    any = ( ...args ) => args.some( a => !!a ),
    all = ( ...args ) => args.every( a => !!a );`, { next: true } );
```

So the `const` has something to do with it. I haven't taken a look inside your code being too busy at the moment. These errors might have to make me use `esprima` or something else for a bit until they get resolved but I'll keep checking in and switch back when things work. If I get some time, I might even take a look for a fix. I like the idea of a JavaScript parser module that seems to care about staying up-to-date with the language.

I'm getting the impression that you're actively maintaining this module so I figured I'd throw these errors your way. (See what I did there?)

> Julian

**Comment by KFlash** [comment]
Hi. Thanks for your report! As stated in the readme I normaly promise around 30 min from my reply to the issue are solved. This can take a little longer, but I'm diving into this now.

**Comment by KFlash** [comment]
@julianjensen I just pushed a solution for this issue now to NPM. So closing. The *removed**  EA implementation will be done separated and should not affect your. code. And feel free to contribute anytime if you want!
