### ISSUE TITLE
Arrow parameters must not contain yield expressions

### ISSUE THREAD

**Issue by rilut** [cherow/cherow#50]
### Steps to reproduce

This fails:

```js
var c = require('cherow')
var a =`
(class Service extends Component.mixin(AsyncEmitter) {
    *addEndpoint(name, handler) {
        yield this.emit("beforeEndpointAdded", name, handler, this);
        if (!this._endpoints[name]) {
            this._endpoints[name] = {};
            this._express.use("/" + name, (req, res, next) => {
                if (this._endpoints[name].handler)
                    return this._endpoints[name].handler(req, res, next);
                else
                    return next();
            });
        }
    }
})`
c.parse(a)
```

### Expected output

```js
> c.parse(a)
{ type: 'Program',
  body: [ { type: 'ExpressionStatement', expression: [Object] } ],
  sourceType: 'script' }
```

### Actual output
```
Error: Line 4: Arrow parameters must not contain yield expressions
    at constructError (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:292:17)
    at createError (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:313:17)
    at Parser.error (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:443:29)
    at Parser.parseParenthesizedExpression (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:4507:20)
    at Parser.parsePrimaryExpression (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:3932:25)
    at Parser.parseMemberExpression (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:3538:44)
    at Parser.parseLeftHandSideExpression (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:3529:25)
    at Parser.parseUpdateExpression (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:3444:17)
    at Parser.parseUnaryExpression (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:3390:21)
    at Parser.parseBinaryExpression (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:3346:44)
```

### Notes

The arrow parameters does not contains `yield`, rather `yield` is located on the line above the if block.

**Comment by KFlash** [comment]
@rilut I will fix this shortly. Give me *max* 1 hour.

**Comment by KFlash** [comment]
@rilut A fix is up. Both here and on NPM. Sorry delays. I normally fix issues within 30 minutes after they are reported, but this time I was in the middle of another fix.

Closing!

**Comment by rilut** [comment]
That was really fast...... Thank you!
