### ISSUE TITLE
Cherow doesn't handle loop declaration scope correctly

### ISSUE THREAD

**Issue by rilut** [cherow/cherow#51]
### Steps to reproduce

This fails:

```js
var c = require('cherow')
var a=`
(class ServiceApi extends Component.mixin(AsyncEmitter) {
    *initialize() {
        for (let v in apiDesc) { }
        for (let v in this._api) { }
    }
})`
c.parse(a)
```

### Expected output

```js
> c.parse(a)
{ type: 'Program',
  body: [ { type: 'ExpressionStatement', expression: [Object] } ],
  sourceType: 'script' }
```

### Actual output
```
Error: Line 7: 'v' has already been declared
    at constructError (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:292:17)
    at createError (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:313:17)
    at Parser.error (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:444:23)
    at Parser.addFunctionArg (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:4727:16)
    at Parser.parseBindingIdentifier (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:4846:18)
    at Parser.parseBindingPatternOrIdentifier (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:4828:25)
    at Parser.parseVariableDeclaration (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:3071:19)
    at Parser.parseVariableDeclarationList (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:3061:22)
    at Parser.parseForStatement (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:2707:33)
    at Parser.parseStatement (/Users/rilut/myproject/node_modules/cherow/dist/cherow.js:2433:25)
```

**Comment by KFlash** [comment]
Thanks for your report! Download latest from NPM and your issue should have been solved. Closing!
