### ISSUE TITLE
C-style let in for() loop throws redeclaration error

### ISSUE THREAD

**Issue by apaprocki** [cherow/cherow#9]
`let` in the `for()` loop should be scoped to the block.

Script:

```
$ cat let.js
for (let i = 0; i < 10; ++i) {
    console.log(i);
}
for (let i = 0; i < 10; ++i) {
    console.log(i);
}
```

Error:

```
./node_modules/cherow/dist/cherow.js:700
    throw createError.apply(void 0, [ type, this.trackErrorLocation() ].concat( params ));
    ^
Error: Line 4: 'i' has already been declared
    at constructError (./node_modules/cherow/dist/cherow.js:432:17)
    at createError (./node_modules/cherow/dist/cherow.js:453:17)
    at Parser.error (./node_modules/cherow/dist/cherow.js:700:23)
    at Parser.addBlockName (./node_modules/cherow/dist/cherow.js:5082:14)
    at Parser.addVarOrBlock (./node_modules/cherow/dist/cherow.js:5056:14)
    at Parser.parseBindingIdentifier (./node_modules/cherow/dist/cherow.js:3652:10)
    at Parser.parseBindingPatternOrIdentifier (./node_modules/cherow/dist/cherow.js:3616:25)
    at Parser.parseVariableDeclaration (./node_modules/cherow/dist/cherow.js:3136:19)
    at Parser.parseVariableDeclarationList (./node_modules/cherow/dist/cherow.js:3171:22)
    at Parser.parseForOrForInOrForOfStatement (./node_modules/cherow/dist/cherow.js:2598:33)
```

**Comment by KFlash** [comment]
@apaprocki A fix is up. So I'm closing this one and adding the task to my TODO.
